version: '3.9'

services:
  app:
    build:
      context: ./docker/php
    container_name: crm_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - crm_network
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: crm_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - crm_network

  db:
    image: mariadb:10.11
    container_name: crm_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - crm_network

  mailpit:
    image: axllent/mailpit
    container_name: crm_mailpit
    ports:
      - "8025:8025"
    networks:
      - crm_network

networks:
  crm_network:

volumes:
  db_data:

